export const TCM_STYLES = `
.r4-tcm-manager,.r4-tcm-badge,.r4-tcm-modal,.r4-tcm-audit-panel{box-sizing:border-box;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;color:#f4f4f4!important}
.r4-tcm-manager *,.r4-tcm-badge *,.r4-tcm-modal *,.r4-tcm-audit-panel *{box-sizing:border-box}
.r4-tcm-manager{margin:0;padding:0;border:1px solid #4b4b4b;border-radius:12px;background:linear-gradient(180deg,rgba(27,27,29,.99),rgba(16,16,18,.99));box-shadow:0 18px 55px #000c;color:#f4f4f4!important;height:100%;display:flex;flex-direction:column;overflow:hidden;transition:box-shadow .16s ease,transform .16s ease}
.r4-tcm-header{display:flex;gap:12px;align-items:center;justify-content:space-between;color:#f4f4f4!important;min-height:54px;padding:10px 14px;border-bottom:1px solid #343438;background:rgba(18,18,20,.96)}
.r4-tcm-brand{display:flex;align-items:center;gap:10px;min-width:0}.r4-tcm-brand-mark{color:#b33b38;font-size:16px;filter:drop-shadow(0 0 7px #b33b3855)}.r4-tcm-brand div{display:flex;flex-direction:column;line-height:1.05}.r4-tcm-brand span{font-size:9px;letter-spacing:.18em;color:#aaa!important}.r4-tcm-brand strong{font-size:13px;letter-spacing:.06em;color:#fff!important}
.r4-tcm-header-right{display:flex;align-items:center;gap:5px}.r4-tcm-window-controls{display:flex;align-items:center;gap:4px}.r4-tcm-window-btn,.r4-tcm-icon-btn{min-width:30px;height:30px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #48484d;border-radius:7px;background:#27272b;color:#f1f1f3!important;cursor:pointer;font-size:15px;line-height:1;padding:0;transition:background .14s ease,border-color .14s ease,transform .14s ease}.r4-tcm-window-btn:hover,.r4-tcm-icon-btn:hover{background:#343439;border-color:#65656b}.r4-tcm-window-btn:active,.r4-tcm-icon-btn:active{transform:scale(.96)}
.r4-tcm-health{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:4px}.r4-tcm-health-ok{background:#63d467;box-shadow:0 0 7px #63d46788}.r4-tcm-health-warn{background:#e2b84d}.r4-tcm-health-bad{background:#ef6262}.r4-tcm-health-idle{background:#777}.r4-tcm-attention-btn{position:relative}.r4-tcm-attention-btn span{position:absolute;right:-5px;top:-5px;min-width:15px;height:15px;border-radius:10px;background:#b33b38;color:white!important;font-size:9px;display:flex;align-items:center;justify-content:center}
.r4-tcm-manager-body{display:flex;flex:1;min-height:0;flex-direction:column;overflow:auto;padding:14px;gap:12px}.r4-tcm-feedback{margin:0}.r4-tcm-stale{background:#5a3d13;color:#ffe9bd!important;padding:9px 10px;border:1px solid #8d6423;border-radius:8px}.r4-tcm-error{background:#531f22;color:#ffd7d7!important;padding:9px 10px;border:1px solid #79353a;border-radius:8px}.r4-tcm-info{background:#173247;color:#d9efff!important;padding:9px 10px;border:1px solid #29516e;border-radius:8px}.r4-tcm-success{background:#173c22;color:#dcffdd!important;padding:9px 10px;border:1px solid #2e673c;border-radius:8px}
.r4-tcm-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.r4-tcm-metrics>div{background:#111114;border:1px solid #343438;border-radius:9px;padding:9px 11px;min-width:0}.r4-tcm-metrics strong{display:block;font-size:18px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#fff!important}.r4-tcm-metrics span{display:block;margin-top:2px;font-size:9px;letter-spacing:.12em;color:#96969d!important}
.r4-tcm-primary-card{padding:15px;border-radius:11px;border:1px solid #47474d;background:radial-gradient(circle at 90% 0,#b33b381b,transparent 36%),#141416;text-align:center}.r4-tcm-eyebrow{font-size:9px;letter-spacing:.17em;color:#b8b8bd!important}.r4-tcm-primary-name{font-size:24px;font-weight:750;margin:4px 0 1px;color:#fff!important}.r4-tcm-primary-reason{font-size:12px;color:#bcbcc1!important;margin-bottom:12px}.r4-tcm-train-primary{width:min(440px,100%);min-height:44px;border:1px solid #438b4a;border-radius:9px;background:linear-gradient(180deg,#397c40,#2d6333);color:#fff!important;font-weight:800;letter-spacing:.04em;cursor:pointer;box-shadow:0 7px 18px #0005;transition:filter .15s ease,transform .15s ease}.r4-tcm-train-primary:hover:not(:disabled){filter:brightness(1.14);transform:translateY(-1px)}.r4-tcm-train-primary:disabled{opacity:.42;cursor:not-allowed}.r4-tcm-paid-progress{font-size:11px;color:#d1b671!important;margin-top:8px}
.r4-tcm-section-head{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:10px;font-weight:750;letter-spacing:.11em;color:#aaa!important}.r4-tcm-link-btn{border:0;background:transparent;color:#b9b9c0!important;font:inherit;cursor:pointer;padding:3px 5px}.r4-tcm-link-btn:hover{color:#fff!important}.r4-tcm-queue,.r4-tcm-roster{background:#121214;border:1px solid #343438;border-radius:10px;padding:11px}.r4-tcm-queue ol{list-style:none;margin:8px 0 0;padding:0}.r4-tcm-queue li{display:grid;grid-template-columns:24px minmax(90px,1fr) auto;gap:8px;align-items:center;min-height:30px;border-top:1px solid #29292d;font-size:12px}.r4-tcm-queue li:first-child{border-top:0}.r4-tcm-queue-rank{color:#73737a!important}.r4-tcm-queue-name{font-weight:700;color:#eee!important}.r4-tcm-queue-reason{color:#a9a9b0!important;text-align:right}
.r4-tcm-table-wrap{overflow:auto;flex:1;min-height:0;margin-top:8px}.r4-tcm-table{width:100%;border-collapse:collapse;font-size:12px;color:#f4f4f4!important}.r4-tcm-table th,.r4-tcm-table td{padding:8px 6px;border-bottom:1px solid #333338;text-align:left;vertical-align:middle;color:#f4f4f4!important}.r4-tcm-table th{font-weight:700;background:#19191c;position:sticky;top:0;z-index:1;color:#bdbdc3!important}.r4-tcm-row-next{background:#27402155}.r4-tcm-row-ineligible{background:rgba(100,20,20,.13)}.r4-tcm-row-pending{background:rgba(120,93,20,.13)}.r4-tcm-row-toggle{border:0;background:transparent;color:#fff!important;text-align:left;cursor:pointer;padding:0}.r4-tcm-row-toggle strong{display:block}.r4-tcm-row-toggle .r4-tcm-muted{font-size:10px}.r4-tcm-row-reason{display:block;margin-top:3px;font-size:10px;color:#a7a7ad!important}.r4-tcm-row-actions{text-align:right!important;white-space:nowrap}.r4-tcm-hidden-action{position:absolute!important;width:1px!important;height:1px!important;overflow:hidden!important;clip:rect(0 0 0 0)!important;white-space:nowrap!important}.r4-tcm-detail-row[hidden]{display:none}.r4-tcm-detail-row td{background:#0e0e10!important}.r4-tcm-detail-grid{display:grid;grid-template-columns:repeat(3,minmax(100px,1fr));gap:8px 14px;padding:6px}.r4-tcm-detail-grid span{display:flex;flex-direction:column;color:#c8c8ce!important}.r4-tcm-detail-grid b{font-size:9px;letter-spacing:.06em;color:#7f7f86!important;text-transform:uppercase;margin-bottom:2px}
.r4-tcm-chip{display:inline-flex;align-items:center;border-radius:999px;padding:3px 7px;font-size:9px;font-weight:800;letter-spacing:.04em;border:1px solid transparent}.r4-tcm-chip-ok{color:#89e18c!important;background:#173c22;border-color:#2e673c}.r4-tcm-chip-next{color:#b7f5b9!important;background:#214d22;border-color:#438b4a}.r4-tcm-chip-paid{color:#efd591!important;background:#3f3315;border-color:#695824}.r4-tcm-chip-priority{color:#d9d3ff!important;background:#30284e;border-color:#51447b}.r4-tcm-chip-warn{color:#ffe397!important;background:#493a13;border-color:#77601d}.r4-tcm-chip-bad{color:#ffabab!important;background:#4b1e22;border-color:#79353a}.r4-tcm-chip-neutral{color:#d6d6dc!important;background:#2b2b30;border-color:#494950}
.r4-tcm-status-ok{color:#7cff4f!important;font-weight:700}.r4-tcm-status-bad{color:#ff6b6b!important;font-weight:700}.r4-tcm-status-warn{color:#ffe45c!important;font-weight:700}.r4-tcm-muted{color:#c7c7c7!important;opacity:1}.r4-tcm-reason{display:block;font-size:11px;margin-top:2px;color:#e8e8e8!important}.r4-tcm-manager strong{color:#fff!important}
.r4-tcm-btn{border:1px solid #555;border-radius:7px;padding:7px 10px;background:#2b2b30;color:#f4f4f4!important;cursor:pointer;font-weight:650}.r4-tcm-btn:hover:not(:disabled){filter:brightness(1.16)}.r4-tcm-btn:disabled{opacity:.45;cursor:not-allowed}.r4-tcm-btn-primary{background:#356b28}.r4-tcm-btn-danger{background:#743134}.r4-tcm-btn-warn{background:#6b551b}.r4-tcm-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}
.r4-tcm-modal-backdrop{position:fixed;inset:0;background:#000c;display:flex;align-items:center;justify-content:center;z-index:10000000;padding:16px}.r4-tcm-modal{width:min(560px,100%);max-height:92vh;overflow:auto;background:#1c1c20;border:1px solid #505057;border-radius:12px;padding:16px;box-shadow:0 18px 60px #000d;color:#f4f4f4!important}.r4-tcm-modal h3{margin:0 0 10px;color:#fff!important}.r4-tcm-modal input,.r4-tcm-modal select{width:100%;padding:8px;background:#111114;color:#eee!important;border:1px solid #515158;border-radius:6px;margin:6px 0}.r4-tcm-modal-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:12px}.r4-tcm-settings-row{margin:10px 0}.r4-tcm-settings-row label{display:block;font-weight:650;margin-bottom:3px}.r4-tcm-settings-check{display:flex;gap:8px;align-items:center}.r4-tcm-settings-check input{width:auto;margin:0}
.r4-tcm-audit-panel{width:min(920px,96vw);max-height:90vh;display:flex;flex-direction:column;overflow:hidden;background:#18181b;border:1px solid #555;border-radius:10px;padding:14px;box-shadow:0 12px 40px #000;color:#f4f4f4!important}.r4-tcm-audit-filters{display:grid;grid-template-columns:minmax(130px,1fr) minmax(160px,1fr) minmax(180px,2fr);gap:10px;margin:12px 0}.r4-tcm-audit-filters label{display:flex;flex-direction:column;gap:4px;font-size:12px;font-weight:700;color:#e8e8e8!important}.r4-tcm-audit-filters select,.r4-tcm-audit-filters input{width:100%;padding:7px 8px;border:1px solid #555;border-radius:5px;background:#111;color:#f4f4f4!important}.r4-tcm-audit-table-wrap{max-height:58vh;overflow:auto;flex:1 1 auto}.r4-tcm-audit-details{max-width:410px;font:11px/1.45 Consolas,Monaco,monospace;overflow-wrap:anywhere;white-space:normal}
.r4-tcm-badge{position:fixed;right:18px;bottom:18px;width:250px;background:#1d1d1df2;border:1px solid #555;border-radius:8px;z-index:999999;padding:10px;box-shadow:0 4px 18px #0009}.r4-tcm-badge-head{display:flex;justify-content:space-between;align-items:center;cursor:move;font-weight:700}.r4-tcm-badge-body{margin-top:8px;font-size:12px;line-height:1.5}.r4-tcm-badge.r4-tcm-collapsed .r4-tcm-badge-body{display:none}
.r4-tcm-floating-shell{z-index:999999!important;resize:both;overflow:hidden;min-width:420px;min-height:280px;max-width:calc(100vw - 16px);max-height:calc(100vh - 16px)}.r4-tcm-floating-shell .r4-tcm-header{cursor:move;user-select:none}.r4-tcm-floating-shell .r4-tcm-window-btn{cursor:pointer;user-select:none}.r4-tcm-floating-shell.r4-tcm-maximized{max-width:none;max-height:none}.r4-tcm-floating-shell.r4-tcm-minimized{display:none!important}
@media(max-width:720px){.r4-tcm-floating-shell{min-width:0;width:calc(100vw - 12px)!important;left:6px!important}.r4-tcm-metrics{grid-template-columns:repeat(3,1fr)}.r4-tcm-primary-name{font-size:21px}.r4-tcm-queue li{grid-template-columns:22px minmax(80px,1fr)}.r4-tcm-queue-reason{grid-column:2;text-align:left;font-size:10px}.r4-tcm-table thead{display:none}.r4-tcm-table,.r4-tcm-table tbody{display:block}.r4-tcm-table tr:not(.r4-tcm-detail-row){display:grid;grid-template-columns:1fr auto;gap:5px;border:1px solid #343438;border-radius:9px;margin:7px 0;padding:9px}.r4-tcm-table tr:not(.r4-tcm-detail-row) td{display:block;border:0;padding:2px}.r4-tcm-table tr:not(.r4-tcm-detail-row) td:nth-child(2){grid-column:1}.r4-tcm-table tr:not(.r4-tcm-detail-row) td:nth-child(3){grid-column:1}.r4-tcm-table tr:not(.r4-tcm-detail-row) td:nth-child(4){grid-column:2;grid-row:1/4}.r4-tcm-icon-btn,.r4-tcm-window-btn{min-width:44px;height:44px}.r4-tcm-detail-grid{grid-template-columns:repeat(2,minmax(100px,1fr))}.r4-tcm-audit-filters{grid-template-columns:1fr}.r4-tcm-audit-panel{width:98vw;max-height:94vh}.r4-tcm-audit-details{max-width:240px}}
@media(prefers-reduced-motion:reduce){.r4-tcm-manager,.r4-tcm-window-btn,.r4-tcm-icon-btn,.r4-tcm-train-primary{transition:none!important}}
`;

export function injectStyles(documentRef = globalThis.document) {
  if (!documentRef?.head || documentRef.getElementById?.("r4-tcm-styles")) return;
  const style = documentRef.createElement("style");
  style.id = "r4-tcm-styles";
  style.textContent = TCM_STYLES;
  documentRef.head.appendChild(style);
}
